// Chinese Character to Pinyin Transliteration Map
// Edit this file to customize character mappings
// Format: '字符': 'pinyin'

const PINYIN_MAP = {
  // Common surnames (sorted by frequency)
  '李': 'li', '王': 'wang', '张': 'zhang', '刘': 'liu', '陈': 'chen',
  '杨': 'yang', '赵': 'zhao', '黄': 'huang', '周': 'zhou', '吴': 'wu',
  '徐': 'xu', '孙': 'sun', '胡': 'hu', '朱': 'zhu', '高': 'gao',
  '林': 'lin', '何': 'he', '郭': 'guo', '马': 'ma', '罗': 'luo',
  '梁': 'liang', '宋': 'song', '郑': 'zheng', '谢': 'xie', '韩': 'han',
  '唐': 'tang', '冯': 'feng', '于': 'yu', '董': 'dong', '萧': 'xiao',
  '程': 'cheng', '曹': 'cao', '袁': 'yuan', '邓': 'deng', '许': 'xu',
  '傅': 'fu', '沈': 'shen', '曾': 'zeng', '彭': 'peng', '吕': 'lv',
  '苏': 'su', '卢': 'lu', '蒋': 'jiang', '蔡': 'cai', '丁': 'ding',
  '魏': 'wei', '叶': 'ye', '钟': 'zhong', '汪': 'wang', '田': 'tian',
  '石': 'shi', '廖': 'liao', '康': 'kang', '白': 'bai', '江': 'jiang',
  '邱': 'qiu', '秦': 'qin', '范': 'fan', '方': 'fang', '孔': 'kong',
  '尹': 'yin', '姚': 'yao', '邵': 'shao', '严': 'yan', '华': 'hua',
  '金': 'jin', '陶': 'tao', '姜': 'jiang', '戚': 'qi', '谢': 'xie',
  '邹': 'zou', '喻': 'yu', '柏': 'bai', '水': 'shui', '窦': 'dou',
  '章': 'zhang', '云': 'yun', '潘': 'pan', '葛': 'ge', '奚': 'xi',
  '彭': 'peng', '郎': 'lang', '鲁': 'lu', '韦': 'wei', '昌': 'chang',
  '苗': 'miao', '凤': 'feng', '花': 'hua', '俞': 'yu', '任': 'ren',
  '袁': 'yuan', '柳': 'liu', '酆': 'feng', '鲍': 'bao', '史': 'shi',
  '唐': 'tang', '费': 'fei', '廉': 'lian', '岑': 'cen', '薛': 'xue',
  '雷': 'lei', '贺': 'he', '倪': 'ni', '汤': 'tang', '滕': 'teng',
  '殷': 'yin', '罗': 'luo', '毕': 'bi', '郝': 'hao', '邬': 'wu',
  '安': 'an', '常': 'chang', '乐': 'le', '时': 'shi', '傅': 'fu',
  '皮': 'pi', '卞': 'bian', '齐': 'qi', '康': 'kang', '伍': 'wu',
  '余': 'yu', '元': 'yuan', '卜': 'bo', '顾': 'gu', '孟': 'meng',
  '平': 'ping', '黄': 'huang', '和': 'he', '穆': 'mu', '萧': 'xiao',
  '尹': 'yin', '姚': 'yao', '邵': 'shao', '湛': 'zhan', '汪': 'wang',
  '祁': 'qi', '毛': 'mao', '禹': 'yu', '狄': 'di', '米': 'mi',
  '贝': 'bei', '明': 'ming', '臧': 'zang', '计': 'ji', '伏': 'fu',
  '成': 'cheng', '戴': 'dai', '谈': 'tan', '宋': 'song', '茅': 'mao',
  '庞': 'pang', '熊': 'xiong', '纪': 'ji', '舒': 'shu', '屈': 'qu',
  '项': 'xiang', '祝': 'zhu', '董': 'dong', '梁': 'liang', '杜': 'du',
  '阮': 'ruan', '蓝': 'lan', '闵': 'min', '席': 'xi', '季': 'ji',
  '麻': 'ma', '强': 'qiang', '贾': 'jia', '路': 'lu', '娄': 'lou',
  '危': 'wei', '童': 'tong', '颜': 'yan', '郭': 'guo', '梅': 'mei',
  '盛': 'sheng', '林': 'lin', '刁': 'diao', '钟': 'zhong', '徐': 'xu',
  '丘': 'qiu', '骆': 'luo', '高': 'gao', '夏': 'xia', '蔡': 'cai',
  '田': 'tian', '樊': 'fan', '胡': 'hu', '凌': 'ling', '霍': 'huo',
  '虞': 'yu', '万': 'wan', '支': 'zhi', '柯': 'ke', '昝': 'zan',
  '管': 'guan', '卢': 'lu', '莫': 'mo', '经': 'jing', '房': 'fang',
  '裘': 'qiu', '缪': 'miao', '干': 'gan', '解': 'xie', '应': 'ying',
  '宗': 'zong', '丁': 'ding', '宣': 'xuan', '贲': 'ben', '郁': 'yu',
  '单': 'dan', '杭': 'hang', '洪': 'hong', '包': 'bao', '诸': 'zhu',
  '左': 'zuo', '石': 'shi', '崔': 'cui', '吉': 'ji', '钮': 'niu',
  '龚': 'gong', '程': 'cheng', '嵇': 'ji', '邢': 'xing', '滑': 'hua',
  '裴': 'pei', '陆': 'lu', '荣': 'rong', '翁': 'weng', '荀': 'xun',
  '羊': 'yang', '於': 'yu', '惠': 'hui', '甄': 'zhen', '曲': 'qu',
  '家': 'jia', '封': 'feng', '芮': 'rui', '羿': 'yi', '储': 'chu',
  '靳': 'jin', '汲': 'ji', '邴': 'bing', '糜': 'mi', '松': 'song',
  '井': 'jing', '段': 'duan', '富': 'fu', '巫': 'wu', '乌': 'wu',
  '焦': 'jiao', '巴': 'ba', '弓': 'gong', '牧': 'mu', '隗': 'wei',
  '山': 'shan', '谷': 'gu', '车': 'che', '侯': 'hou', '宓': 'mi',
  '蓬': 'peng', '全': 'quan', '郗': 'xi', '班': 'ban', '仰': 'yang',
  '秋': 'qiu', '仲': 'zhong', '伊': 'yi', '宫': 'gong', '宁': 'ning',
  '仇': 'chou', '栾': 'luan', '暴': 'bao', '甘': 'gan', '钭': 'tou',
  '厉': 'li', '戎': 'rong', '祖': 'zu', '武': 'wu', '符': 'fu',
  '刘': 'liu', '景': 'jing', '詹': 'zhan', '束': 'shu', '龙': 'long',
  '叶': 'ye', '幸': 'xing', '司': 'si', '韶': 'shao', '郜': 'gao',
  '黎': 'li', '蓟': 'ji', '薄': 'bo', '印': 'yin', '宿': 'su',
  '白': 'bai', '怀': 'huai', '蒲': 'pu', '台': 'tai', '从': 'cong',
  '鄂': 'e', '索': 'suo', '咸': 'xian', '籍': 'ji', '赖': 'lai',
  '卓': 'zhuo', '蔺': 'lin', '屠': 'tu', '蒙': 'meng', '池': 'chi',
  '乔': 'qiao', '阴': 'yin', '郁': 'yu', '胥': 'xu', '能': 'neng',
  '苍': 'cang', '双': 'shuang', '闻': 'wen', '莘': 'shen', '党': 'dang',
  '翟': 'zhai', '谭': 'tan', '贡': 'gong', '劳': 'lao', '逄': 'pang',
  '姬': 'ji', '申': 'shen', '扶': 'fu', '堵': 'du', '冉': 'ran',
  '宰': 'zai', '郦': 'li', '桑': 'sang', '濮': 'pu', '牛': 'niu',
  '寿': 'shou', '通': 'tong', '边': 'bian', '扈': 'hu', '燕': 'yan',
  '冀': 'ji', '郏': 'jia', '浦': 'pu', '尚': 'shang', '农': 'nong',
  '温': 'wen', '别': 'bie', '庄': 'zhuang', '晏': 'yan', '柴': 'chai',
  '翟': 'zhai', '阎': 'yan', '充': 'chong', '慕': 'mu', '连': 'lian',
  '茹': 'ru', '习': 'xi', '宦': 'huan', '艾': 'ai', '鱼': 'yu',
  '容': 'rong', '向': 'xiang', '古': 'gu', '易': 'yi', '慎': 'shen',
  '戈': 'ge', '廖': 'liao', '庾': 'yu', '终': 'zhong', '暨': 'ji',
  '居': 'ju', '衡': 'heng', '步': 'bu', '都': 'du', '耿': 'geng',
  '满': 'man', '弘': 'hong', '匡': 'kuang', '国': 'guo', '文': 'wen',
  '寇': 'kou', '广': 'guang', '禄': 'lu', '阙': 'que', '东': 'dong',
  '殳': 'shu', '沃': 'wo', '利': 'li', '蔚': 'wei', '越': 'yue',
  '夔': 'kui', '隆': 'long', '师': 'shi', '巩': 'gong', '厍': 'she',
  '聂': 'nie', '晁': 'chao', '勾': 'gou', '敖': 'ao', '融': 'rong',
  '冷': 'leng', '訾': 'zi', '辛': 'xin', '阚': 'kan', '那': 'na',
  '简': 'jian', '饶': 'rao', '空': 'kong', '曾': 'zeng', '毋': 'wu',
  '沙': 'sha', '乜': 'mie', '养': 'yang', '鞠': 'ju', '须': 'xu',
  '丰': 'feng', '巢': 'chao', '关': 'guan', '蒯': 'kai', '相': 'xiang',
  '查': 'cha', '后': 'hou', '荆': 'jing', '红': 'hong', '游': 'you',
  '竺': 'zhu', '权': 'quan', '佴': 'er', '盖': 'gai', '益': 'yi',
  '桓': 'huan', '公': 'gong', '万': 'wan', '俟': 'si',

  // Compound surnames (2-character)
  '司马': 'sima', '上官': 'shangguan', '欧阳': 'ouyang', '夏侯': 'xiahou',
  '诸葛': 'zhuge', '闻人': 'wenren', '东方': 'dongfang', '赫连': 'helian',
  '皇甫': 'huangfu', '尉迟': 'yuchi', '公羊': 'gongyang', '公冶': 'gongye',
  '淳于': 'chunyu', '单于': 'chanyu', '申屠': 'shentu', '公孙': 'gongsun',
  '仲孙': 'zhongsun', '轩辕': 'xuanyuan', '令狐': 'linghu', '钟离': 'zhongli',
  '宇文': 'yuwen', '长孙': 'zhangsun', '慕容': 'murong', '鲜于': 'xianyu',
  '闾丘': 'lvqiu', '司徒': 'situ', '亓官': 'qiguan', '司寇': 'sikou',
  '仉督': 'zhangdu', '子车': 'ziche', '颛孙': 'zhuansun', '端木': 'duanmu',
  '巫马': 'wuma', '公西': 'gongxi', '漆雕': 'qidiao', '乐正': 'lezheng',
  '壤驷': 'rangsi', '公良': 'gongliang', '拓跋': 'tuoba', '夹谷': 'jiagu',
  '宰父': 'zaifu', '谷利': 'guli',
};

module.exports = { PINYIN_MAP };
